image: node:20.17.0

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - node
          script:
            - npm install
            - git diff --exit-code
            - cd lib
            - npm run build
            - cd ../Raumbelegung
            - npm run zip
            - cd ../Stadt
            - npm run zip
            - cd ../Calendar
            - npm run zip
          artifacts:
            - dist/*
